# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfX5iQIzP0wc_2zzCvPKiq425deYBK27
"""



"""To load a CSV file from your desktop:

1.  **Upload the file:** You can use the file upload function provided by Google Colab. This will open a file selection dialog in your browser.
2.  **Read with pandas:** Once uploaded, you can use `pandas.read_csv()` to load the data into a DataFrame.
"""

import pandas as pd
from google.colab import files

# Upload the CSV file from your local machine
uploaded = files.upload()

# Assuming you upload one file, get its name
for fn in uploaded.keys():
  print(f'User uploaded file "{fn}"')
  file_name = fn

# Read the uploaded CSV file into a pandas DataFrame
df = pd.read_csv(file_name)

# Display the first 5 rows of the DataFrame
display(df.head())

# The 'file_name' variable already holds the name/path of the uploaded file
print(f"The path to your uploaded file is: {file_name}")

# You can verify that the DataFrame 'df' was successfully loaded using this path
print("Displaying the first 5 rows of the loaded DataFrame:")
display(df.head())

print(df.columns)

df = df.drop(columns=["PassengerId"])

print(df)

print(df["Fare"].min())

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix


X=df.drop(columns=["Survived"])
Y=df["Survived"]

x_train , x_test , y_train , y_test = train_test_split(
    X,Y,test_size=0.2,random_state=42
)

Scaler = StandardScaler()
x_train = Scaler.fit_transform(x_train)
x_test = Scaler.transform(x_test)

model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

y=y_pred = model.predict(x_test)


accuracy = accuracy_score(y_test , y_pred)
conf_metrix = confusion_matrix(y_test , y_pred)


print("accuracy:", accuracy)
print("confusion_metrix\n",conf_metrix)